# Generated by Django 5.1.6 on 2025-03-01 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_article_creator_alter_article_status_and_more"),
    ]

    operations = []
